global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerting_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<private_ip_of_g4dn_instance1>:9100', '<private_ip_of_g4dn_instance2>:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['<private_ip_of_g4dn_instance1>:8080', '<private_ip_of_g4dn_instance2>:8080']

  - job_name: 'gpu_exporter'
    static_configs:
      - targets: ['<private_ip_of_g4dn_instance1>:9400', '<private_ip_of_g4dn_instance2>:9400']