global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "/etc/prometheus/alerting_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_timeout: 10s
    scrape_interval: 15s
    static_configs:
      - targets: ['app-alb-1651614373.us-east-1.elb.amazonaws.com:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '${1}'


  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['app-alb-1651614373.us-east-1.elb.amazonaws.com:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '${1}'


  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']