global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "/etc/prometheus/alerting_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    scheme: 'http'  # Use 'https' if ALB is configured with HTTPS
    static_configs:
      - targets: ['app-alb-1363988340.us-east-1.elb.amazonaws.com:9100']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    scheme: 'http'  # Use 'https' if ALB is configured with HTTPS
    static_configs:
      - targets: ['app-alb-1363988340.us-east-1.elb.amazonaws.com:8080']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

      


  