# /etc/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: production
    datacenter: aws-${AWS_REGION}

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'

# Rule files
rule_files:
  - "rules/recording_rules.yml"
  - "rules/alert_rules_system.yml"
  - "rules/alert_rules_ralph.yml"
  - "rules/alert_rules_business.yml"
  - "rules/alert_rules_ml.yml"

# Remote write configuration (optional)
remote_write:
  - url: "${REMOTE_STORAGE_URL}"
    basic_auth:
      username: "${REMOTE_STORAGE_USER}"
      password: "${REMOTE_STORAGE_PASSWORD}"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: '{__name__=~"(node_.*|ralph_.*|ml_.*)"}'
        action: keep

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '$1'
      - source_labels: [__address__]
        target_label: instance_ip
        replacement: '$1'

  - job_name: 'ralph'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 30s
    scrape_timeout: 25s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ralph-dcim'

  - job_name: 'ml-forecasting'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 60s