# /etc/prometheus/alertmanager.yml
global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-alerts'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 1h
    - match:
        team: data_science
      receiver: 'ds-team'

receivers:
  - name: 'team-alerts'
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
    email_configs:
      - to: 'team@example.com'
        send_resolved: true

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#incidents'
        send_resolved: true
    email_configs:
      - to: 'oncall@example.com'
        send_resolved: true

  - name: 'ds-team'
    slack_configs:
      - channel: '#data-science'
        send_resolved: true
    email_configs:
      - to: 'ds-team@example.com'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']